port: 7331
name: "NightCity Data Exchange"
database: "postgres://postgres:postgres@localhost:7432/nde?initial_pool_size=1&max_pool_size=200&max_idle_pool_size=100&checkout_timeout=2.0&retry_attempts=5&retry_delay=0.5"
